import { IUser } from "./types/user.interface";

export const variables = {
    API_URL: 'https://localhost:7066/api',
    PHOTOS_URL: "https://localhost:7066/photos/",
    SOCKET_URL : "wss://localhost:7066/chat-hub",
    // API_URL: 'https://jeytikon-001-site1.etempurl.com/api',
    // PHOTOS_URL: "https://jeytikon-001-site1.etempurl.com/photos/",
    // SOCKET_URL : "wss://jeytikon-001-site1.etempurl.com/chat-hub",
    USER_LOCALSTORAGE: "user_info",
    THEME_LOCALSTORAGE: "page_theme",
    LANGUAGE_LOCALSTORAGE: "page_language",
    MAX_COLLECTION_PHOTO_SIZE: 5000000,
    ASPECT_COLLECTIONS_IMG: 4/3,
    GET_ACCESS_TOKEN: () => (JSON.parse(localStorage.getItem("user_info")!) as IUser)?.accessToken || '',
    LANGUAGES: [
    {
        ERROR_LOADING_COLLECTION_PHOTO: 'Ошибка загрузки фото коллекции',
        ERROR: 'Ошибка',
        ERROR_ACCESS_TOKEN: 'Ошибка токена доступа',
        COLLECTION_ADDED: 'Коллекция успешно добавлена',
        ERROR_ADDING_COLLECTION: 'Ошибка добавления коллекции',
        INPUT_DATA: 'Введите данные',
        RETURN_TO_THE_CABINET: 'Вернуться в личный кабинет',
        ADD_NEW_COLLECTION: 'Создание новой коллекции',
        COLLECTION_PHOTO: 'Фото коллекции',
        COLLECTION_NAME: 'Название коллекции',
        ENTER_COLLECTION_NAME: 'Введите название коллекции',
        COLLECTION_THEME: 'Тема коллекции',
        ENTER_COLLECTION_THEME: 'Введите тему коллекции',
        COLLECTION_DESCRIPTION: 'Описание в MarkDown (по желанию)',
        ENTER_COLLECTION_DESCRIPTION: 'Введите описание коллекции',
        ADD_COLLECTION_FIELDS: 'Добавьте поля коллекции',
        ADD_FIELD: 'Добавить поле',
        LOADING: 'Загрузка...',
        ADD_COLLECTION: 'Создать колллекцию',
        STRING: 'Строка',
        NUMBER: 'Число',
        DATE: 'Дата',
        BOOLEAN: 'Да/Нет',
        ENTER_FIELD_NAME: 'Введите название поля',
        CROP: 'Обрезать',
        MAX_PHOTO_SIZE: 'Максимальный размер фото - 5 МБ',
        LOGIN:"Вход",
        REGISTER: 'Регистрация',
        INVALID_LOGIN: 'Вы ввели неправильный email или пароль',
        NO_ACCESS: 'Нет доступа',
        SUCCESFULLY_ENTERED: 'Вы успешно вошли',
        ENTER_EMAIL: 'Введите e-mail',
        PASSWORD: 'Пароль',
        ENTER_PASSWORD: 'Введите пароль',
        LOG_IN: 'Войти',
        ALREADY_EXISTS: 'Пользователь с таким адресом эл. почты существует',
        SUCCESFULLY_REGISTERED: 'Вы успешно зарегистрированы',
        SUCCESS: 'Успешно',
        SURNAME: 'Фамилия',
        ENTER_SURNAME: 'Введите фамилию',
        NAME: 'Имя',
        ENTER_NAME: 'Введите имя',
        REGISTER_: 'Зарегистрироваться',
        ERROR_USER_DATA: 'Ошибка в данных пользователя',
        USER_SUCCESSFULLY_DELETED: 'Пользователь успешно удален',
        USER_NOT_FOUND: 'Пользователь не найден',
        USER_SUCCESSFULLY_CHANGED: 'Пользователь успешно изменен',
        SURE_DELETE_ACC: 'Вы точно хотите удалить аккаунт? Вместе с этим вы удалите все его коллекции.',
        DELETE_ACCOUNT: 'Удалить аккаунт',
        DELETING_ACCOUNT: 'Удаление аккаунта',
        ADMIN_MENU: 'Меню администратора',
        SELECTED_USER: 'Выбранный пользователь',
        ROLE: 'Роль',
        USER: 'Пользователь',
        ADMIN: 'Администратор',
        ACCESS: 'Доступ',
        NEW_PASSWORD: 'Новый пароль (По желанию)',
        ENTER_NEW_PASSWORD: 'Введите новый пароль',
        CHANGE_DATA: 'Изменить данные',
        DELETE_USER: 'Удалить пользователя',
        YES: 'Да',
        NO: 'Нет',
        RETURN_TO_MAIN: 'Вернуться на главную',
        MY_DATA: 'Мои данные',
        MY_COLLECTIONS: 'Мои коллекции',
        MY_COMMENTS: 'Мои комментарии',
        MY_REACTIONS: 'Мои реакции',
        LOGOUT: 'Выйти',
        NO_TAGS: 'Нет тегов',
        ERROR_LOAD_COLLECTIONS: 'Ошибка загрузки коллекций',
        CATEGORY: 'Категория:',
        ITEMS: 'Предметов:',
        FIELDS: 'Полей:',
        CREATED: 'Создано:',
        NO_YOUR_COMMENTS: 'Вы еще не оставляли комментариев',
        WRONG_PASSWORD: 'Вы ввели неправильный пароль',
        DATA_SUCCESFULLY_CHANGED: 'Данные успешно изменены',
        ERROR_IN_USER_DATA: 'Ошибка в данных пользователя',
        SURE_DELETE_ACC_MY: 'Вы точно хотите удалить аккаунт? Вместе с этим вы удалите все свои коллекции.',
        ENTER_NEW_SURNAME: 'Введите новую фамилию',
        ENTER_NEW_NAME: 'Введите новое имя',
        ENTER_NEW_EMAIL: 'Введите новый email',
        ENTER_OLD_PASS:'Введите старый пароль',
        OLD_PASS: 'Старый пароль (Обязательно)',
        NO_YOUR_REACTIONS:'Вы еще не оставляли реакций',
        COLLECTION_CHANGED: 'Коллекция успешно изменена',
        RETURN_TO_COLLECTION: 'Вернуться к коллекции',
        CHANGE_COLLECTION: 'Изменение коллекции',
        CHANGE_COLLECTION_: 'Изменить коллекцию',
        COLLECTION_NOT_FOUND: 'Коллекция не найдена'
    },
    {
        ERROR_LOADING_COLLECTION_PHOTO: 'Loading collection photo error',
        ERROR: 'Error',
        ERROR_ACCESS_TOKEN: 'Access token error',
        COLLECTION_ADDED: 'Collection succesfully added',
        ERROR_ADDING_COLLECTION: 'Adding collection error',
        INPUT_DATA: 'Input data',
        RETURN_TO_THE_CABINET: 'Return to the cabinet',
        ADD_NEW_COLLECTION: 'Add new collection',
        COLLECTION_PHOTO: 'Collection photo',
        COLLECTION_NAME: 'Collection name',
        ENTER_COLLECTION_NAME: 'Input collection name',
        COLLECTION_THEME: 'Collection theme',
        ENTER_COLLECTION_THEME: 'Input collection theme',
        COLLECTION_DESCRIPTION: 'Description in MarkDown (optional)',
        ENTER_COLLECTION_DESCRIPTION: 'Input collection description',
        ADD_COLLECTION_FIELDS: 'Add collection fields',
        ADD_FIELD: 'Add field',
        LOADING: 'Loading...',
        ADD_COLLECTION: 'Add collection',
        STRING: 'String',
        NUMBER: 'Number',
        DATE: 'Date',
        BOOLEAN: 'Yes/No',
        ENTER_FIELD_NAME: 'Input field name',
        CROP: 'Crop',
        MAX_PHOTO_SIZE: 'MAX PHOTO SIZE - 5 MB',
        LOGIN:"Log In",
        REGISTER: 'Sign Up',
        INVALID_LOGIN: 'You\'ve entered invalid email or password',
        NO_ACCESS: 'No access',
        SUCCESFULLY_ENTERED: 'You\'ve succesfully entered',
        ENTER_EMAIL: 'Input e-mail',
        PASSWORD: 'Password',
        ENTER_PASSWORD: 'Input password',
        LOG_IN: 'Log In',
        ALREADY_EXISTS: 'User with that email already exists',
        SUCCESFULLY_REGISTERED: 'You\'ve succesfully registered',
        SUCCESS: 'Success',
        SURNAME: 'Surname',
        ENTER_SURNAME: 'Input surname',
        NAME: 'Name',
        ENTER_NAME: 'Input name',
        REGISTER_: 'Sign Up',
        ERROR_USER_DATA: 'User data error',
        USER_SUCCESSFULLY_DELETED: 'User successfully deleted',
        USER_NOT_FOUND: 'User not found',
        USER_SUCCESSFULLY_CHANGED: 'User successfully changed',
        SURE_DELETE_ACC: 'Are you sure you want to delete an account? You will also delete all of his collections.',
        DELETE_ACCOUNT: 'Delete an account',
        DELETING_ACCOUNT: 'Account deleting',
        ADMIN_MENU: 'Admin menu',
        SELECTED_USER: 'Selected user',
        ROLE: 'Role',
        USER: 'User',
        ADMIN: 'Admin',
        ACCESS: 'Access',
        NEW_PASSWORD: 'New password (Optional)',
        ENTER_NEW_PASSWORD: 'Input new password',
        CHANGE_DATA: 'Change data',
        DELETE_USER: 'Delete user',
        YES: 'Yes',
        NO: 'No',
        RETURN_TO_MAIN: 'Return to main page',
        MY_DATA: 'My info',
        MY_COLLECTIONS: 'My collections',
        MY_COMMENTS: 'My comments',
        MY_REACTIONS: 'My reactions',
        LOGOUT: 'Log out',
        NO_TAGS: 'No tags',
        ERROR_LOAD_COLLECTIONS: 'Error collections load',
        CATEGORY: 'Category:',
        ITEMS: 'Items:',
        FIELDS: 'Fields:',
        CREATED: 'Created:',
        NO_YOUR_COMMENTS: 'There are no your comments yet',
        WRONG_PASSWORD: 'You\'ve entered wrong password',
        DATA_SUCCESFULLY_CHANGED: 'Info succesfully changed',
        ERROR_IN_USER_DATA: 'Error in user data',
        SURE_DELETE_ACC_MY: 'Are you sure you want to delete an account? You will also delete all of your collections.',
        ENTER_NEW_SURNAME: 'Input new surname',
        ENTER_NEW_NAME: 'Input new name',
        ENTER_NEW_EMAIL: 'Input new email',
        ENTER_OLD_PASS:'Input old password',
        OLD_PASS: 'Old password (necessary)',
        NO_YOUR_REACTIONS:'There are no your reactions yet',
        COLLECTION_CHANGED: 'Collection succesfully changed',
        RETURN_TO_COLLECTION: 'Return to the collection',
        CHANGE_COLLECTION: 'Change collection',
        CHANGE_COLLECTION_: 'Change collection',
        COLLECTION_NOT_FOUND: 'Collection not found'
    }
]
}